name: webfeed_plus

description: webfeed_plus is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication namespaces are also supported.
homepage: https://github.com/OmkarDabade/webfeed_plus

version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  xml: ^6.3.0
  intl: 

dev_dependencies:
  flutter_lints: ^2.0.2
  http:
